### ISSUE TITLE
Question : How do I set the body of each step of wizard?

### ISSUE THREAD

**Issue by atifwaqar** [timeu/timeu-wizard#2]
Hi, 
I'm new to polymer and I'm finding it difficult to set the `Step Body`.
i.e.
I have 4 steps : 
1. Get Personal Info (Fname,Lname,Gender,Age,etc)
2. Get Credit Card info
3. User Account Preferences 
4. Welcome On-board Message

Now each step have its own Page/Body/Div. How do i set that?

**Comment by timeu** [comment]
If I understand you correctly you want to switch the content based on the wizard step ? 

You can use data-binding together with `iron-pages` to switch the content.

**Comment by atifwaqar** [comment]
Yes exactly, but I'm still not able to achieve that. 
It would be so kind of you if you show a tiny code snippet.

**Comment by atifwaqar** [comment]
Please ignore the question. I found the correct syntax. I'll write it here so if anyone new to Polymer (like me) needs it : 

```
        <timeu-wizard id="default" steps='["Step1","Step2","Step3","Step4","Step5"]' step="{{model.WizardStep$}}">
        </timeu-wizard>
        <iron-pages selected="{{model.WizardStep$}}">
            <div>Step 0 page (The wizard is not started yet)</div>
            <div>Step 1 page</div>
            <div>Step 2 page</div>
            <div>Step 3 page</div>
            <div>Step 4 page</div>
            <div>Step 5 page</div>
            <paper-button raised id="next">Next</paper-button>
        </iron-pages>
```
