### ISSUE TITLE
Typo on active border-color

### ISSUE THREAD

**Issue by krsnadjava25** [timeu/timeu-wizard#3]
You mistype the mixin for element styling.

## Expected outcome

`border-color` should use mixin `--timeu-wizard-active-color`

## Actual outcome

It's `--time-wizard-active-color`

## How-to

Edit file `timeu-wizard.html` line 192, 205, and 218

## Comment

Great element btw :) Good job!

**Comment by timeu** [comment]
Thx for the bug report and sorry for the delay should be fixed now
